#!/bin/bash
## 用来显示本地/服务器Web应用日志内容
## 示例 checklog -p modulequality -h gd212  或者 checklog

target_host=localhost		## 服务器
target_project=""		## 项目名称

## 获取主机名
while getopts h:p: params
do
	case $params in
	h)
		target_host=$OPTARG
		;;
	p)
		target_project=$OPTARG
		;;
	esac
done

if [ -z "$target_host" ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 没有指定目标服务器.")}'
	exit 1
fi

if [ -z "$target_project" ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 没有指定目标项目名称.")}'
	exit 1
fi

## 读取配置文件中服务器信息. 如果配置文件中存在任何错误, 则在这一步就会报错
cd $SUBSCRIPT_PATH/awk ## 进入awk程序根目录
serverInfo=`gawk -f server.awk -v server=$target_host -v project=$target_project $GDLTCONFIG`

if [ $? -ne 0 ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 读取配置文件服务器信息时出错, 错误信息请查看[**server.awk**]日志信息.")}'
	exit 1
fi

for line in `echo $serverInfo`
do
	eval $line
done

## 输出日志
if [ $target_host == "localhost" ]; then
	tail -f $_server_log
else
	ssh $target_host "tail -f $_server_log"
fi
