#!/bin/bash
## 用于检查本地/服务器上的tomcat是否已经启动
## 示例 process -h gd212 -p modulequality 或者 process

target_host=localhost		## 服务器
target_project=""		## 项目名称

## 获取主机名
while getopts h:p: params
do
	case $params in
	h)
		target_host=$OPTARG
		;;
	p)
		target_project=$OPTARG
		;;
	esac
done

if [ -z "$target_host" ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 没有指定目标服务器.")}'
	exit 1
fi

if [ -z "$target_project" ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 没有指定目标项目名称.")}'
	exit 1
fi

## 读取配置文件中服务器信息. 如果配置文件中存在任何错误, 则在这一步就会报错
cd $SUBSCRIPT_PATH/awk ## 进入awk程序根目录
serverInfo=`gawk -f server.awk -v server=$target_host -v project=$target_project $GDLTCONFIG`

if [ $? -ne 0 ]; then
	gawk -f $LOG_MAKER -e 'BEGIN {LogMark("Error: [**launchapp**] 读取配置文件服务器信息时出错, 错误信息请查看[**server.awk**]日志信息.")}'
	exit 1
fi

for line in `echo $serverInfo`
do
	eval $line
done


if [ $target_host == "localhost" ]; then
	process=`ps -ef | grep $_server_path | awk '$8 !~ /^grep/ {print $2}'`
else
	process=`ssh $target_host "ps -ef | grep $_server_path | awk '\\$8 !~ /^grep/ {print \\$2}'"`
fi
echo $process
