#!/bin/bash
## 用于检查本地/服务器上的tomcat是否已经启动
## 示例 process -h gd212 -p modulequality 或者 process

host=localhost		## 服务器
tomcatsuffix=_tomcat	## tomcat路径变量后缀名
project=""		## 项目名称

## 运行配置文件
source $GDLTCONFIG

## 获取主机名
while getopts h:p: params
do
	case $params in
	h)
		host=$OPTARG
		;;
	p)
		project='_'$OPTARG
		;;
	esac
done

process=""
if [ $host == "localhost" ]; then
	process=`pgrep -a java | grep $TOMCAT_HOME`
else
	if [ -z $project ]; then
		echo 没有指定项目名称
		exit 1
	fi

	eval tomcatpath='$'$host$project$tomcatsuffix
	if [ -z "$tomcatpath" ]; then
		echo 没有在配置文件中找到项目$project在服务器$host下的tomcat地址
		exit 1
	fi

	process=`ssh $host "pgrep -a java | grep $tomcatpath"`
fi

echo $process
